---
jobs:
  build:
    name: Build
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: pod install --no-repo-update --verbose
        shell: bash
      - name: Setup certs
        uses: apple-actions/import-codesign-certs@v1
        with:
          p12-file-base64: ${{ secrets.SDK_TEAM_P12 }}
          p12-password: ${{ secrets.SDK_TEAM_PASS }}
      - name: Build4Testing
        run: base64 -d ${{ secrets.SDK_HOST_MOBILEPROVISION }} -o ~/Library/MobileDevice/Provisioning\ Profiles/SDKHost.mobileprovision | mkdir ~/tmp | xcodebuild -workspace ~/work/ios-emarsys-sdk/ios-emarsys-sdk/EmarsysSDK.xcworkspace -scheme Tests -configuration Debug -destination generic/platform=iOS build-for-testing -allowProvisioningUpdates -derivedDataPath ~/tmp
        shell: bash
      - name: Test
        uses: sersoft-gmbh/xcodebuild-action@v1
        with:
          action: build-for-testing
          destination: platform=iOS Simulator,name=iPhone 11
          scheme: Tests
          workspace: EmarsysSDK.xcworkspace
name: Last commit build
'on':
  push:
    branches:
      - master
  workflow_dispatch: null