name: Last commit build

on:
  workflow_dispatch:  
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache cocoapods
        uses: actions/cache@v2
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods
          restore-keys: |
            ${{ runner.os }}-pods
      - name: Install Dependencies
        run: pod install --no-repo-update --verbose
        shell: bash
#       - name: Build for Testing
#         uses: sersoft-gmbh/xcodebuild-action@v1
#         with:
#           workspace: EmarsysSDK.xcworkspace
#           scheme: Tests
#           destination: generic/platform=iOS 
#           action: build-for-testing
#           allow-provisioning-updates: true
      
