name: Last commit build

on:
  workflow_dispatch:  
  push:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: macOS-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: pod --version
        shell: bash
    
      
